######################################################################
# Automatically generated by qmake (2.01a) Wed Jun 19 18:47:11 2013
######################################################################
TEMPLATE = app
QT      += widgets xml network
QT      += core websockets


CONFIG		+= console
#CONFIG		-= console
TARGET		= wfax-module
QMAKE_CXXFLAGS	+= -std=c++17 
QMAKE_CFLAGS	+= -flto -ffast-math 
QMAKE_CXXFLAGS	+= -flto -ffast-math 
QMAKE_LFLAGS	+= -flto
#QMAKE_CFLAGS	+= -g
#QMAKE_CXXFLAGS	+= -g
#QMAKE_LFLAGS	+= -g
#QMAKE_CXXFLAGS	+= -fsanitize=address
#QMAKE_CFLAGS	+= -fsanitize=address
#QMAKE_LFLAGS	+= -fsanitize=address
RC_ICONS	=  skimmer.ico
RESOURCES       += resources.qrc

DEPENDPATH += .  \
	      input \
	      filters \
	      support

INCLUDEPATH += .  \
	      input \
	      filters \
	      support

#CONFIG += static

# Input
HEADERS += ./radio.h \
	   ./constants.h \
	   ./super-frame.h \
	   ./fax-params.h\
           ./fax-shifter.h \
	   ./fax-image.h \
	   ./fax-scroller.h \
	   ./support/ringbuffer.h \
	   ./support/preset-handler.h \
	   ./filters/decimator.h \
	   ./filters/decimator-25.h \
	   ./filters/fax-bandfilter.h \
	   ./filters/lowpassfilter.h \
	   ./filters/up-filter.h \
           ./input/message-handler.h \
           ./input/socket-handler.h \
	   ./input/oscillator.h 

FORMS	+= ./fax-decoder.ui 

SOURCES += ./main.cpp \
	   ./radio.cpp \
	   ./super-frame.cpp \
	   ./fax-shifter.cpp \
	   ./fax-image.cpp \
	   ./fax-scroller.cpp \
	   ./support/preset-handler.cpp \
	   ./filters/decimator.cpp \
	   ./filters/decimator-25.cpp \
	   ./filters/fax-bandfilter.cpp \
           ./filters/lowpassfilter.cpp \
           ./filters/up-filter.cpp \
           ./input/message-handler.cpp \
           ./input/socket-handler.cpp \
	   ./input/oscillator.cpp 

unix {
exists ("./.git") {
	GITHASHSTRING = $$system(git rev-parse --short HEAD)
	!isEmpty(GITHASHSTRING) {
	message("Current git hash = $$GITHASHSTRING")
	DEFINES += GITHASH=\\\"$$GITHASHSTRING\\\"
   }
}
isEmpty(GITHASHSTRING) {
    DEFINES += GITHASH=\\\"------\\\"
}

DESTDIR		= ./linux-bin
LIBS		+= -L/usr/lib64
LIBS		+= -L/lib64
}

win32 {
exists ("./.git") {
   GITHASHSTRING = $$system(git rev-parse --short HEAD)
   !isEmpty(GITHASHSTRING) {
       message("Current git hash = $$GITHASHSTRING")
       DEFINES += GITHASH=\\\"$$GITHASHSTRING\\\"
   }
}
isEmpty(GITHASHSTRING) {
    DEFINES += GITHASH=\\\"------\\\"
}

DESTDIR		= /d/systems/sdrconnect-plugins/wfax-plugin
LIBS    += -lwinmm
}
